### ISSUE TITLE
'prisma generate' does not generate client with MongoDB provider

### ISSUE THREAD

**Issue by esall** [RobertCraigie/prisma-client-py#324]
## Bug description

The Prisma client fails to generate when using the CLI under Windows when using MongoDB as provider.
Even with logging enabled, there is no additional logging output.

## How to reproduce

Using Powershell:
1. cd C:/Temp
2. python -m venv .venv
3. .venv/Scripts/Activate.ps1
4. pip install prisma
5. prisma generate

```
(.venv) PS C:\Temp> prisma generate
Prisma schema loaded from schema.prisma
```

6. Verify that no files have been changed in C:/Temp/.venv/Lib/site-packages/prisma.

## Expected behavior

I expected client.py and the various other output files to be generated in .venv/Lib/site-packages/prisma.

## Prisma information

schema.prisma
```prisma
// database
datasource mongodb {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

// generator
generator client {
  provider = "prisma-client-py"
  interface = "asyncio"
  previewFeatures = ["mongoDb"]
}

// data models
model User {
  @@map("users")

  uuid                  String       @id @default(uuid()) @map("_id")

  dateCreated           DateTime?    @default(now())
  dateModified          DateTime?    @updatedAt
  email                 String?
  name                  String
}
```

## Environment & setup

- OS: Windows 10
- Database: MongoDB
- Python version: 3.9.6
- Prisma version: 3.9.1

```
prisma               : 3.9.1
prisma client python : 0.6.2
platform             : windows
engines              : bcc2ff906db47790ee902e7bbc76d7ffb1893009
install path         : C:\Temp\.venv\Lib\site-packages\prisma
installed extras     : []
```

Output of `prisma -v generate`:

```
prisma                : 3.9.1
@prisma/client        : Not found
Current platform      : windows
Query Engine (Binary) : query-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ..\Users\Me\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine      : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ..\Users\Me\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-migration-engine-windows.exe, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine  : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ..\Users\Me\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-introspection-engine-windows.exe, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary         : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ..\Users\Me\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-prisma-fmt-windows.exe, resolved by PRISMA_FMT_BINARY)
Default Engines Hash  : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                : 0.457.0
```

**Comment by RobertCraigie** [comment]
The windows platform is not officially supported yet and as such there will be some quirks that haven't been ironed out yet. `prisma generate` not propagating generator error messages is a known issue (https://github.com/prisma/prisma/issues/10270) but if I remember correctly this is the only issue I ran into when testing on windows.

To show the error message you need to set the environment variables `PRISMA_PY_DEBUG` to `1` and `DEBUG` to `*`. You should then be able to see the full error message. Please let me know what this outputs so I can help further.

**Comment by esall** [comment]
Hi @RobertCraigie,

I know it is experimental, but it used to work in older versions of your Prisma client. :)
I managed to get the additional logging output, here it is:
```
(.venv) PS C:\temp> prisma generate
[DEBUG  ] prisma.binaries.binaries: query-engine cached at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: migration-engine cached at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-migration-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: introspection-engine cached at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-introspection-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: prisma-fmt cached at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-prisma-fmt-windows.exe
[DEBUG  ] prisma.binaries.binaries: prisma-cli-windows.exe cached at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-cli-windows.exe
[DEBUG  ] prisma.binaries.binaries: All binaries are cached
[DEBUG  ] prisma.cli.prisma: Using Prisma CLI at C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-cli-windows.exe
[DEBUG  ] prisma.cli.prisma: Running prisma command with args: ['generate']
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe +0ms
  prisma:download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-migration-engine-windows.exe +18ms
  prisma:download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-introspection-engine-windows.exe +1ms
  prisma:download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-prisma-fmt-windows.exe +1ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./.env +1ms
Environment variables loaded from .env
Prisma schema loaded from schema.prisma
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe +0ms
  prisma:getConfig Using CLI Query Engine (Binary) at: C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe +0ms
  prisma:getDMMF Using CLI Query Engine (Binary) at: C:\Users\Eric\AppData\Local\Temp\prisma\binaries\engines\bcc2ff906db47790ee902e7bbc76d7ffb1893009\prisma-query-engine-windows.exe +0ms
  prisma:getGenerators neededVersions {} +0ms
  prisma:GeneratorProcess [DEBUG  ] prisma.generator.jsonrpc: Replied with {"id": 1, "jsonrpc": "2.0", "result": {"manifest": {"prettyName": "Prisma Client Python (v0.6.2)", "defaultOutput": "c:\\temp\\.venv\\lib\\site-packages\\prisma", "denylist": null, "requiresEngines": null, "requiresGenerators": null}}} +0ms
  prisma:GeneratorProcess Traceback (most recent call last): +99ms
  prisma:GeneratorProcess   File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main +1ms
  prisma:GeneratorProcess     return _run_code(code, main_globals, None, +6ms
  prisma:GeneratorProcess   File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code +15ms
  prisma:GeneratorProcess     exec(code, run_globals) +1ms
  prisma:GeneratorProcess   File "C:\temp\.venv\Scripts\prisma-client-py.exe\__main__.py", line 7, in <module> +0ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\cli\cli.py", line 51, in main +1ms
  prisma:GeneratorProcess     Generator.invoke() +1ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\generator.py", line 74, in invoke +0ms
  prisma:GeneratorProcess     generator.run() +1ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\generator.py", line 125, in run +15ms
  prisma:GeneratorProcess     self.generate(data) +14ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\generator.py", line 215, in generate +3ms
  prisma:GeneratorProcess     render_template(rootdir, name, params) +7ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\generator.py", line 256, in render_template +21ms
  prisma:GeneratorProcess     output = template.render(**params) +9ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\jinja2\environment.py", line 1291, in render +19ms
  prisma:GeneratorProcess     self.environment.handle_exception() +20ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception +5ms
  prisma:GeneratorProcess     raise rewrite_traceback_stack(source=source) +3ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\templates\actions.py.jinja", line 85, in top-level template code +1ms
  prisma:GeneratorProcess     'SELECT * FROM {{ model.name }} WHERE {{ field.name }} = {{ sql_param() }}', +1ms
  prisma:GeneratorProcess   File "c:\temp\.venv\lib\site-packages\prisma\generator\models.py", line 113, in sql_param +1ms
  prisma:GeneratorProcess     raise RuntimeError('no-op') +0ms
  prisma:GeneratorProcess RuntimeError: no-op +1ms
```

**Comment by RobertCraigie** [comment]
Ah I see thank you!

This is a result of https://github.com/RobertCraigie/prisma-client-py/issues/142, I had forgotten that this code path would break on MongoDB, sorry about that.

As a short term fix I'll disable the raw query methods for MongoDB and I'll look into supporting raw queries in the future.

**Comment by esall** [comment]
> As a short term fix I'll disable the raw query methods for MongoDB and I'll look into supporting raw queries in the future.

Sounds good to me, thanks!

**Comment by RobertCraigie** [comment]
@esall You should now be able to use MongoDB if you install from `main`, e.g.

```
pip install -U git+https://github.com/RobertCraigie/prisma-client-py
```

Thanks for the bug report!
