### ISSUE TITLE
Improve error message for unsupported composite types

### ISSUE THREAD

**Issue by yatochka-dev** [RobertCraigie/prisma-client-py#672]
## Bug description

When I'am running prisma generate or prisma db push, I'm getting this error: 
```bash
Prisma schema loaded from prisma\schema.prisma
Error: 
Traceback (most recent call last):
  File "P:\PyCharm\Projects\fainobot\venv\lib\site-packages\prisma\generator\generator.py", line 111, in run
    self._on_request(request)
  File "P:\PyCharm\Projects\fainobot\venv\lib\site-packages\prisma\generator\generator.py", line 169, in _on_request
    self.generate(data)
    raise rewrite_traceback_stack(source=source)
  File "P:\PyCharm\Projects\fainobot\venv\lib\site-packages\prisma\generator\templates\actions.py.jinja", line 168, in top-level template code
    '{{ field.name }}': {{ field.get_sample_data() }},
  File "P:\PyCharm\Projects\fainobot\venv\lib\site-packages\prisma\generator\models.py", line 966, in get_sample_data
    sampled = self._get_sample_data()
  File "P:\PyCharm\Projects\fainobot\venv\lib\site-packages\prisma\generator\models.py", line 1005, in _get_sample_data
    raise RuntimeError(f'Sample data not supported for {typ} yet')
RuntimeError: Sample data not supported for GuildSettings yet
```

## Expected behavior

I want it to just work, I don't really understand this error.

## Prisma information

```prisma
generator client {
    provider = "prisma-client-py"
    interface = "asyncio"
    recursive_type_depth = -1
}

datasource db {
  provider = "mongodb"
  url      =
}



// This model represents a discord guild

model Guild {
    snowflake String @id @map("_id")
    members   Member[]
    settings GuildSettings
}


// This model represents discord's user

model User {
    snowflake String @id @map("_id") 
    members   Member[]
}

// This model represents a member of a guild, like user, but inside of a guild
 
model Member {
    id String @id @default(auto()) @map("_id") @db.ObjectId

    user   User  @relation(fields: [userId], references: [snowflake])
    userId String 
    guild   Guild  @relation(fields: [guildId], references: [snowflake])
    guildId String
}

type GuildSettings {
    language String
}

 
```

## Environment & setup

- OS: Windows 11
- Database: Mongo DB
- Python version: python 3.10.6 
- Prisma version: 0.8.0v

```
prisma                  : 4.8.0
prisma client python    : 0.8.0
platform                : windows
expected engine version : d6e67a83f971b175a593ccc12e15c4a757f93ffe
install path            : P:\PyCharm\Projects\fainobot\venv\Lib\site-packages\prisma
installed extras        : []
```

**Comment by RobertCraigie** [comment]
Ah sorry about this. That error is because we don't support composite types in MongoDB yet.

That error message definitely need improvement.

**Comment by yatochka-dev** [comment]
> Ah sorry about this. That error is because we don't support composite types in MongoDB yet.
> 
> That error message definitely need improvement.

Will it be added in future version(0.9.0)?

**Comment by RobertCraigie** [comment]
@yatochka-dev Support will be added in a future version but it is not currently a priority. See #314 for tracking support.
