### ISSUE TITLE
Compatibility with Render.com

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#735]
## Bug description

Deploying a FastAPI application to [render.com](https://render.com) will not work. Minimal repo can be found here: https://github.com/RobertCraigie/prisma-python-render

## How to reproduce

Setup referenced repo on render.com, this error is encountered:

```
Mar 25 08:00:07 PM  INFO:     Waiting for application startup.
Mar 25 08:00:07 PM  ERROR:    Traceback (most recent call last):
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
Mar 25 08:00:07 PM      async with self.lifespan_context(app) as maybe_state:
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
Mar 25 08:00:07 PM      await self._router.startup()
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
Mar 25 08:00:07 PM      await handler()
Mar 25 08:00:07 PM    File "/opt/render/project/src/main.py", line 19, in startup
Mar 25 08:00:07 PM      await prisma.connect()
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/client.py", line 239, in connect
Mar 25 08:00:07 PM      datasources=datasources,
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/query.py", line 128, in connect
Mar 25 08:00:07 PM      self.file = file = self._ensure_file()
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/query.py", line 116, in _ensure_file
Mar 25 08:00:07 PM      return utils.ensure(BINARY_PATHS.query_engine)
Mar 25 08:00:07 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/utils.py", line 113, in ensure
Mar 25 08:00:07 PM      + 'Try running prisma py fetch'
Mar 25 08:00:07 PM  prisma.engine.errors.BinaryNotFoundError: Expected /opt/render/project/src/prisma-query-engine-debian-openssl-1.1.x, /opt/render/.cache/prisma-python/binaries/4.11.0/8fde8fef4033376662cad983758335009d522acb/prisma-query-engine-debian-openssl-1.1.x or /opt/render/.cache/prisma-python/binaries/4.11.0/8fde8fef4033376662cad983758335009d522acb/node_modules/prisma/query-engine-debian-openssl-1.1.x to exist but none were found.
Mar 25 08:00:07 PM  Try running prisma py fetch
Mar 25 08:00:07 PM  
Mar 25 08:00:07 PM  ERROR:    Application startup failed. Exiting.
Mar 25 08:00:44 PM  ==> Starting service with 'PRISMA_PY_DBEUG=1 uvicorn main:app --log-level debug'
Mar 25 08:00:51 PM  INFO:     Started server process [53]
Mar 25 08:00:51 PM  INFO:     Waiting for application startup.
Mar 25 08:00:51 PM  ERROR:    Traceback (most recent call last):
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
Mar 25 08:00:51 PM      async with self.lifespan_context(app) as maybe_state:
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
Mar 25 08:00:51 PM      await self._router.startup()
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
Mar 25 08:00:51 PM      await handler()
Mar 25 08:00:51 PM    File "/opt/render/project/src/main.py", line 19, in startup
Mar 25 08:00:51 PM      await prisma.connect()
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/client.py", line 239, in connect
Mar 25 08:00:51 PM      datasources=datasources,
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/query.py", line 128, in connect
Mar 25 08:00:51 PM      self.file = file = self._ensure_file()
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/query.py", line 116, in _ensure_file
Mar 25 08:00:51 PM      return utils.ensure(BINARY_PATHS.query_engine)
Mar 25 08:00:51 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prisma/engine/utils.py", line 113, in ensure
Mar 25 08:00:51 PM      + 'Try running prisma py fetch'
Mar 25 08:00:51 PM  prisma.engine.errors.BinaryNotFoundError: Expected /opt/render/project/src/prisma-query-engine-debian-openssl-1.1.x, /opt/render/.cache/prisma-python/binaries/4.11.0/8fde8fef4033376662cad983758335009d522acb/prisma-query-engine-debian-openssl-1.1.x or /opt/render/.cache/prisma-python/binaries/4.11.0/8fde8fef4033376662cad983758335009d522acb/node_modules/prisma/query-engine-debian-openssl-1.1.x to exist but none were found.
Mar 25 08:00:51 PM  Try running prisma py fetch
Mar 25 08:00:51 PM  
Mar 25 08:00:51 PM  ERROR:    Application startup failed. Exiting.
```

The last path referenced in that error message does exist and can be executed.

## Expected behavior

Should work out of the box.

**Comment by Chipzstar** [comment]
Solution that worked for me was to change the default location where the binaries are cached.

CONTEXT: In render the default location is /opt/render/.cache/prisma-python/binaries/. Unfortunatley the .cache directory never gets created during the build. My guess is because in Render special permissions are needed to create folders/files that start with "." such as ".cache".

SOLUTION: create a custom folder to store the binaries and set the path to the env variable PRISMA_BINARY_CACHE_DIR
e.g. PRISMA_BINARY_CACHE_DIR=/opt/render/project/src/.binaries. /opt/render/project/src/ is the root location of your project code. The .binaries folder was manually created.

(see the Binary Cache Directory section at https://prisma-client-py.readthedocs.io/en/stable/reference/config/#config-options)
