### ISSUE TITLE
UnprocessableEntityError: 422: Error occurred, it is likely that the internal GraphQL query builder generated a malformed request

### ISSUE THREAD

**Issue by ayanez17** [RobertCraigie/prisma-client-py#770]
## Bug description

When trying to hit an endpoint that uses Prisma I get the following error:
```
127.0.0.1 - - [13/Jun/2023 08:29:18] "GET /user HTTP/1.1" 308 -
GET
127.0.0.1 - - [13/Jun/2023 08:29:18] "GET /user/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/mycomputer/code/company/server/api/routes/user.py", line 11, in list_create
    users = User.prisma().find_many()
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/prisma/actions.py", line 469, in find_many
    resp = self._client._execute(
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/prisma/client.py", line 418, in _execute
    return self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/prisma/engine/query.py", line 226, in query
    return self.request(
  File "/Users/mycomputer/code/company/venv/lib/python3.9/site-packages/prisma/engine/http.py", line 128, in request
    raise errors.UnprocessableEntityError(resp)
prisma.engine.errors.UnprocessableEntityError: 422: Error occurred, it is likely that the internal GraphQL query builder generated a malformed request.
Please create an issue at https://github.com/RobertCraigie/prisma-client-py/issues
```
## How to reproduce
I run `python server/api/index.py`
I use postman to hit the following endpoint: `http://127.0.0.1:5000/user`
`index.py`
```
from flask import Flask
from prisma import Prisma, register
from routes.user import user_blueprint

db = Prisma()
db.connect()
register(db)

app = Flask(__name__)


@app.route("/", methods=["GET"])
def index():
    return {"ping": "pong"}


app.register_blueprint(user_blueprint, url_prefix="/user")

if __name__ == "__main__":
    app.run(debug=True, port=5000, threaded=True)

```
`user.py`
```
from flask import Blueprint, request
from prisma.models import User, UserInfo

user_blueprint = Blueprint("user", __name__)


@user_blueprint.route("/", methods=["GET"])
def list_create():
    if request.method == "GET":
        print(request.method)
        users = User.prisma().find_many()
        print(users)
        return {"data": [user.dict() for user in users]}

```

## Expected behavior
I expect to get a list of all users or an empty list.

## Prisma information

```
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["jsonProtocol"]
}

generator server {
    provider             = "prisma-client-py"
    recursive_type_depth = 5
    interface            = "sync"
}

datasource db {
    provider = "postgres"
    url      =  url      = "postgresql://postgres:@localhost:5432/mydb"
}

enum Role {
    SELLER
    BUYER
    ADMIN
}

model User {
    id         String    @id @default(cuid())
    createdAt  DateTime  @default(now())
    firstname  String
    lastname   String
    email      String    @unique
    role       Role[]
    userinfo   UserInfo?
}

model UserInfo {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    phone     String   @unique
    address   String
    state     String
    // relations
    userId    String   @unique
    user      User     @relation(fields: [userId], references: [id])
}

```

## Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Python version: Python 3.9.16
- Prisma version:
```
prisma                  : 4.15.0
prisma client python    : 0.9.0
platform                : darwin
expected engine version : 8fbc245156db7124f997f4cecdd8d1219e360944

```

**Comment by RobertCraigie** [comment]
Thanks for the bug report!
