### ISSUE TITLE
Docker installation of Prisma CLI gets stuck for prebuilt node (20.4.0)

### ISSUE THREAD

**Issue by Ali-Parandeh** [RobertCraigie/prisma-client-py#784]
## Bug description

Docker installation of Prisma CLI gets stuck for prebuilt node (20.4.0). Never resolves.

```bash
Installing Prisma CLI
/usr/local/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
 * Install prebuilt node (20.4.0) ..

```

## How to reproduce

Use this dockerfile

```
FROM python:3.11.0-slim as production

ENV APP_DIR=/code

ENV PYTHONUNBUFFERED 1

WORKDIR $APP_DIR

RUN apt-get update

COPY ./requirements.txt $APP_DIR/requirements.txt
RUN pip install --no-cache-dir --upgrade -r $APP_DIR/requirements.txt

COPY ./schema.prisma $APP_DIR/schema.prisma
COPY ./migrations $APP_DIR/migrations

ENTRYPOINT ["prisma", "-v"]

```

-->

## Expected behavior

Should build it. Last working version of prebuilt node (0.19.3)

```bash
Install prebuilt node (20.3.1) ..... done.
```

## Prisma information

Requirements File 

```txt
prisma==0.9.1
```

Error

```python
Generating Prisma Client types for mypy
Installing Prisma CLI
 * Install prebuilt node (19.7.0) .Incomplete read while readingfrom https://nodejs.org/download/release/v19.7.0/node-v19.7.0-linux-x64.tar.gz
.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1519, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 1104, in main
    create_environment(env_dir, args)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 980, in create_environment
    install_node(env_dir, src_dir, args)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 739, in install_node
    install_node_wrapped(env_dir, src_dir, args)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 762, in install_node_wrapped
    download_node_src(node_url, src_dir, args)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 602, in download_node_src
    with ctx as archive:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/nodeenv.py", line 573, in tarfile_open
    tf = tarfile.open(*args, **kwargs)
  File "/usr/local/lib/python3.10/tarfile.py", line 1630, in open
    saved_pos = fileobj.tell()
AttributeError: 'bytes' object has no attribute 'tell'

```

## Environment & setup

- OS: Ventura 13.4.1 (22F82)
- Database: SQL Server
- Python version: 3.11
- Prisma version: 0.9.1

**Comment by Ali-Parandeh** [comment]
Seems to be the node server downtime

Closing

**Comment by Ali-Parandeh** [comment]
But before I do is there way to force prebuilt node version version?

**Comment by caelx** [comment]
I ran into the same issue, thought my builds were broken.  It would be helpful if there was more debug information to figure out what the issue is.

**Comment by tyteen4a03** [comment]
+1 - ran into this issue as well.

**Comment by tyteen4a03** [comment]
FYI - using nodejs-bin seems to have worked around the issue: https://pypi.org/project/nodejs-bin/
