### ISSUE TITLE
Pydantic Import Error - needs upgrade?

### ISSUE THREAD

**Issue by simondpalmer** [RobertCraigie/prisma-client-py#806]
## Bug description

Pydantic Import Error: `BaseSettings` has been moved to the `pydantic-settings` package

## How to reproduce
pip installed supabase and this may of upgraded pydantic creating a conflict with current Prisma Python client?

## Expected behavior

Flask run to work

## Import Error information

```
try 'flask run --help' for help.

Error: While importing 'main.py', an ImportError was raised:

Traceback (most recent call last):
  File "c:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\Users\Simon Palmer\Documents\Programming\ideally-api\main.py", line 9, in <module>
    from prisma import Prisma, Json
  File "c:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\lib\site-packages\prisma\__init__.py", line 11, in <module>
    from ._config import config as config
  File "c:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\lib\site-packages\prisma\_config.py", line 7, in <module>
    from pydantic import BaseSettings, Extra, Field
  File "c:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
  File "c:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.2/u/import-error
```
Also errors when trying to just running 
````
prisma py version comes up with the followning error:
```
Traceback (most recent call last):
  File "C:\Users\Simon Palmer\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Simon Palmer\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon Palmer\Documents\Programming\ideally-api\.venv\Scripts\prisma.exe\__main__.py", line 4, in <module>
  File "c:\users\simon palmer\documents\programming\ideally-api\.venv\lib\site-packages\prisma\__init__.py", line 11, in <module>      
    from ._config import config as config
  File "c:\users\simon palmer\documents\programming\ideally-api\.venv\lib\site-packages\prisma\_config.py", line 7, in <module>        
    from pydantic import BaseSettings, Extra, Field
  File "c:\users\simon palmer\documents\programming\ideally-api\.venv\lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
  File "c:\users\simon palmer\documents\programming\ideally-api\.venv\lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```
```

## Environment & setup

- OS:  Windows
- Python version: 3.9
- Prisma version: 0.8.2


```

```

**Comment by RobertCraigie** [comment]
Hey @simondpalmer, this is happening because you're using pydantic v2 which is unfortunately not supported yet. It also appears you're not on the latest version which correctly pins the pydantic dependency.

See #791 for tracking.
