### ISSUE TITLE
Query engine seems to stop before disconnecting

### ISSUE THREAD

**Issue by NixBiks** [RobertCraigie/prisma-client-py#851]
## Bug description

I have an application that needs to exit gracefully on keyboard interrupt. After the CTRL+C some db calls are needed. However the query engine server seems to be closed by that time.

## How to reproduce

Here is a small repro example

```python
import asyncio

from prisma import Prisma


async def main():
    db = Prisma()
    await db.connect()

    try:
        while True:
            await asyncio.sleep(10)
    except (KeyboardInterrupt, asyncio.CancelledError):
        await db.log.find_many()
        await db.disconnect()


asyncio.run(main())
```

## Expected behavior

I'd expect `await db.log.find_many()` to run just fine since it's called before disconnecting. It breaks though

## Prisma information

```prisma
model Log {
  id        BigInt   @id @default(autoincrement())

  @@map("logs")
}
```

## Environment & setup

- OS: macOS
- Database: PostgresSQL
- Python version: 3.12
- Prisma version:

```
prisma                  : 5.4.2
@prisma/client          : Not found
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at node_modules/.pnpm/@prisma+engines@5.4.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at node_modules/.pnpm/@prisma+engines@5.4.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.4.1-2.ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Default Engines Hash    : ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Studio                  : 0.494.0
```

**Comment by RobertCraigie** [comment]
Thanks for the report, I don't think this is an issue with this library as I can reproduce the same issue just using httpx.

```py
import asyncio
from httpx import AsyncClient

async def main():
    client = AsyncClient()

    try:
        while True:
            await asyncio.sleep(10)
    except (KeyboardInterrupt, asyncio.CancelledError):
        response = await client.get('https://example.com')
        print(response)


asyncio.run(main())
```

You may find more information in the httpx repo, https://github.com/encode/httpx.

**Comment by NixBiks** [comment]
That example works just fine for me `httpx@0.24.1`. Are you sure the issue isn't with this library @RobertCraigie ?

**Comment by RobertCraigie** [comment]
@NixBiks hmm, I get this error using `httpx==0.25.0` and `httpcore==0.18.0` with my httpx only script.

```
^CTraceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/foo.py", line 13, in main
    response = await client.get('https://example.com')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 221, in connect_tcp
    await event.wait()
  File "/Users/robert/code/prisma-client-py/.direnv/python-3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robert/code/prisma-client-py/foo.py", line 17, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by NixBiks** [comment]
Super odd! And we are both on macOS it seems. Are you running in a virtual environment? I'm running in a clean virtual environment

```
╭─ ~/Projects/nix/test ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✘ INT  3.11.4 at 11:27:52
╰─❯ poetry show --tree 
httpcore 0.18.0 A minimal low-level HTTP client.
├── anyio >=3.0,<5.0
│   ├── idna >=2.8 
│   └── sniffio >=1.1 
├── certifi *
├── h11 >=0.13,<0.15
└── sniffio ==1.*
httpx 0.25.0 The next generation HTTP client.
├── certifi *
├── httpcore >=0.18.0,<0.19.0
│   ├── anyio >=3.0,<5.0 
│   │   ├── idna >=2.8 
│   │   └── sniffio >=1.1 
│   ├── certifi * 
│   ├── h11 >=0.13,<0.15 
│   └── sniffio ==1.* (circular dependency aborted here)
├── idna *
└── sniffio *

╭─ ~/Projects/nix/test ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✘ INT  3.11.4 at 11:25:34
╰─❯ poetry run python --version
Python 3.11.4

╭─ ~/Projects/nix/test ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  3.11.4 at 11:25:07
╰─❯ poetry run python wip.py               
^C<Response [200 OK]>
```
