### ISSUE TITLE
Pydantic >2.0 makes `prisma generate` crash

### ISSUE THREAD

**Issue by monarchwadia** [RobertCraigie/prisma-client-py#858]
Thank you for the awesome work on this project.

## Bug description

Prisma Generate fails when using Pydantic >2.0 because of a warning

## How to reproduce

* Step 1. In a project with an existing prisma.schema, install Prisma as well as Pydantic > 2.0. 
* Step 2. Run `prisma generate`

Generation fails with the following error, and no Prisma classes are generated.

```
(.venv) monarch@Monarch-Legion:~/workspace/startedup/backend$ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
Traceback (most recent call last):
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/prisma/generator/generator.py", line 112, in run
    self._on_request(request)
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/prisma/generator/generator.py", line 170, in _on_request
    self.generate(data)
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/prisma/generator/generator.py", line 268, in generate
    render_template(rootdir, name, params)
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/prisma/generator/generator.py", line 309, in render_template
    output = template.render(**params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/prisma/generator/templates/client.py.jinja", line 42, in top-level template code
    BINARY_PATHS = model_parse(BinaryPaths, {{ binary_paths.dict(by_alias=True) }})
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monarch/workspace/startedup/backend/.venv/lib/python3.12/site-packages/typing_extensions.py", line 2498, in wrapper
    warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
pydantic.warnings.PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
```

## Expected behavior

Should generate Prisma classes and not print error

## Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider             = "prisma-client-py"
  interface            = "asyncio"
  recursive_type_depth = 5
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id               String             @id @default(uuid())
  is_admin         Boolean            @default(false)
  email            String             @unique
  password         String             @unique
  created_at       DateTime           @default(now())
  updated_at       DateTime           @updatedAt
  GeneratedContent GeneratedContent[]
}

model GeneratedContent {
  id         String   @id @default(uuid())
  content    String
  user       User     @relation(fields: [user_id], references: [id])
  user_id    String
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

## Environment & setup

- OS: WSL on Windows
- Database: PostgreSQL
- Python version: Tested with 3.11.4 and 3.12
- Prisma version:

```
prisma                  : 5.4.2
prisma client python    : 0.11.0
platform                : debian-openssl-1.1.x
expected engine version : ac9d7041ed77bcc8a8dbd2ab6616b39013829574
```

**Comment by nateostro** [comment]
would love to use prisma py, but this issue is forcing us to use a different solution for our ORM

**Comment by RobertCraigie** [comment]
For some reason I can't reproduce this....

Running this command doesn't emit any warnings but I know it should...
```
python -W error -m prisma generate --schema=tests/data/schema.prisma
```

Any ideas? I will fix this soon but I would like to make sure this can't happen in the future
