### ISSUE TITLE
Avoid writing to `site-packages/prisma`

### ISSUE THREAD

**Issue by ethanabrooks** [RobertCraigie/prisma-client-py#916]
## Problem

By default, the operation `prisma db push` operation writes to `site-packages/prisma`. This causes issues for nix users, whose nix store is read only:
```
nix-shell-env ❯ prisma db push                       
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

The database is already in sync with the Prisma schema.

Running generate... - Prisma Client Python (v0.12.0)

Some types are disabled by default due to being incompatible with Mypy, it is highly recommended
to use Pyright instead and configure Prisma Python to use recursive types. To re-enable certain types:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}

If you need to use Mypy, you can also disable this message by explicitly setting the default value:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = 5
}

For more information see: https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/#default-type-limitations

Traceback (most recent call last):
  File "/nix/store/s16v3cd2dzg07kjpp7bchb8wp69mwjrv-python3.11-prisma-0.12.0/lib/python3.11/site-packages/
prisma/generator/generator.py", line 108, in run
    self._on_request(request)
  File "/nix/store/s16v3cd2dzg07kjpp7bchb8wp69mwjrv-python3.11-prisma-0.12.0/lib/python3.11/site-packages/
prisma/generator/generator.py", line 161, in _on_request
    self.generate(data)
  File "/nix/store/s16v3cd2dzg07kjpp7bchb8wp69mwjrv-python3.11-prisma-0.12.0/lib/python3.11/site-packages/
prisma/generator/generator.py", line 240, in generate
    shutil.copy(data.schema_path, packaged_schema)
  File "/nix/store/pwr22740f2pv36q5g28l1gjdg1bw43zm-python3-3.11.7/lib/python3.11/shutil.py", line 419, in
 copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/pwr22740f2pv36q5g28l1gjdg1bw43zm-python3-3.11.7/lib/python3.11/shutil.py", line 258, in
 copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/nix/store/s16v3cd2dzg07kjpp7bchb8wp69mwjrv-python3.11-pri
sma-0.12.0/lib/python3.11/site-packages/prisma/schema.prisma'
```

## Suggested solution

Perhaps this already exists, but there should be some option to configure the path where this write operation is performed.

Thanks!

**Comment by RobertCraigie** [comment]
Hey @ethanabrooks, this is already supported! You just have to specify a custom `output` directory, https://www.prisma.io/docs/orm/prisma-schema/overview/generators
